name: ci-sales-system-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #this is a github repository
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go test
      - run: go build