name: ci-sales-system-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # this is a github repository
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go test
     
    # docker docs: https://github.com/marketplace/actions/build-and-push-docker-images
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # this secrets we can define on github -> settings -> secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: diegoclair/sampamodas-system:latest